apiVersion: v1
kind: ConfigMap
metadata:
  name: library-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
---
apiVersion: v1
kind: Secret
metadata:
  name: library-secrets
type: Opaque
stringData:
  db-connection-string: "Server=sqlserver;Database=LibraryDb;User Id=sa;Password=REPLACE_ME;TrustServerCertificate=True;"
  email-password: "REPLACE_ME"
