apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
  - ../../base/api-deployment.yaml
  - ../../base/api-service.yaml
  - ../../base/ingress.yaml
  - ../../base/configmap-secrets.yaml

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: library-api
      spec:
        replicas: 3
        template:
          spec:
            containers:
              - name: library-api
                resources:
                  requests:
                    memory: "512Mi"
                    cpu: "500m"
                  limits:
                    memory: "1Gi"
                    cpu: "1000m"
